Databases:
  # tell pyannote.database where to find AMI wav files.
  # {uri} is a placeholder for the session name (eg. ES2004c).
  # you might need to update this line to fit your own setup.
  CMU: dataset/{uri}

Protocols:
  CMU:
    SpeakerDiarization:
      noisy:
        train:
            uri: lists/list_new/train.txt
            annotation: rttm/train.rttm
            annotated: uems/data.uem
        development:
            uri: lists/list_new/dev.txt
            annotation: rttm/dev.rttm
            annotated: uems/data.uem
        test:
            uri: lists/list_new/test.txt
            annotation: rttm/eval.rttm
            annotated: uems/data.uem

      crosstalk:
        train:
            uri: lists/list_new/train.txt
            annotation: rttm/train.rttm
            annotated: uems/data.uem
        development:
            uri: lists/list_new/dev.txt
            annotation: rttm/dev.rttm
            annotated: uems/data.uem
        test:
            uri: lists/list_new/test.txt
            annotation: rttm/eval.rttm
            annotated: uems/data.uem
